import { useState } from "react";
import writer from './img/writer.png';

function App() {
  const [prompt, setPrompt] = useState('')
  const defaultData = {
    prompt: `Write a poem about ${prompt}`,
    temperature: 0.5,
    max_tokens: 75,
    top_p: 1.0,
    frequency_penalty: 0.0,
    presence_penalty: 0.0,
  }
  const handleInput = (e) => {
    setPrompt(e.target.value)
  }
  const engineOptions = {
    0: "text-ada-001",
    1: "text-babbage-001",
    2: "text-curie-001",
    3: "text-davinci-002"
  }
  const engineIQ = ['Simple', 'Average', 'Moderate', 'Profound']
  const [currentEngine, setCurrentEngine] = useState('Moderate')
  const handleEngines = (e) => {
    setSelectedEngine(engineOptions[engineIQ.indexOf(e.target.value)])
    setCurrentEngine(e.target.value)
  }
  const engineIQMap = engineIQ.map((item, key) => {
    return (
      <button key={key} onClick={handleEngines} value={item} className="bg-fuchsia-400 hover:bg-fuchsia-500 active:bg-fuchsia-500 duration-200 ease-in-out p-2 text-white text-base font-bold rounded ">{item}</button>
    )
  })
  const [selectedEngine, setSelectedEngine] = useState(engineOptions[2])
  const [resList, setResList] = useState([])
  const handleButton = (e) => {
    e.preventDefault()
    fetch(`https://api.openai.com/v1/engines/${selectedEngine}/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${process.env.REACT_APP_GPT3_KEY}`,
      },
      body: JSON.stringify(defaultData),
    })
    .then(res => res.json())
    .then(data => {
      setResList([[prompt, data.choices[0].text, currentEngine], ...resList]);
    });
  }
  const handleDelete = (e) => {
    const resFilter = resList?.filter((item) => {
      return item[0] + ',' + item[2] !== e.target.value 
    })
    setResList(resFilter)
  }
  const resMap = resList?.map((each, key) => {
    return (
      <li key={key} className="w-1/3 bg-amber-300 hover:bg-amber-200 duration-200 ease-in-out p-6 rounded text-blue-800 font-black list-none flex flex-col" >
        <p className="text-2xl text-violet-500 mb-4">Prompt:</p>
        <p className="mb-3">"{each[0]}"</p>
        <p className="text-2xl text-violet-500 mb-4">Option:</p>
        <p className="mb-3">{each[2]}</p>
        <p className="whitespace-pre-line	"><span className="text-2xl text-violet-500">Response: </span>{each[1]}</p>
        <button onClick={handleDelete} className="bg-fuchsia-400 hover:bg-fuchsia-500 duration-200 ease-in-out p-2 font-bold text-white rounded mt-5" value={[each[0], each[2]]}>Delete</button>
      </li>
    )
  })

  return (
    <div className="flex justify-center items-center w-full pt-10">
      <div className="flex flex-col justify-center items-center w-3/4 gap-5">
        <div className="flex flex-col justify-center items-center gap-3">
          <div className="w-1/2 flex flex-col">
            <img src={writer} alt="writer" />
            <span className="text-xs self-end">Illustration by <a href="https://icons8.com/illustrations/author/lZpGtGw5182N" target="_blank" rel="noreferrer">Elisabet Guba</a> from <a href="https://icons8.com/illustrations" target="_blank" rel="noreferrer">Ouch!</a></span>  
          </div>
          <div className="w-1/2">
            <h1 className="text-4xl font-black text-center text-violet-600">How about a poem?</h1>
            <div className="text-violet-700 flex flex-col gap-3 my-4">
              <p>Thanks to the power of <a href="https://openai.com/blog/gpt-3-apps/" target="_blank" rel="noreferrer" className="font-bold" >OpenAI's GPT-3</a> we can generate unique poems that are completely computer generated by simply providing some topics as to what we want our poem to be about.</p>
              <p>In the form below enter any topic or details you'd like to include. The AI is designed to consider your selection as if it was being told "Write a poem about ..." </p>
              <p>For some more fun, adjust the depth of 'knowledge' the system will utilize by selecting from the options below.</p>
            </div>
            <div className="flex flex-col items-center gap-3">
              <h3 className="text-center font-black text-violet-600 text-2xl my-2">Options</h3>
              <div className="flex gap-3">
                {engineIQMap}
              </div>
              <div>
                <p className="text-center text-violet-600 font-bold">Selected Option: <span className="text-xl text-fuchsia-600">{currentEngine}</span></p>
              </div>
            </div>
          </div>
        </div>
        <form onSubmit={handleButton} className="flex flex-col w-3/4 items-center gap-2">
          <textarea rows="7" onChange={handleInput} value={prompt} placeholder='What is your poem about? Try "happiness" or "love" or both!' className="w-full text-center bg-fuchsia-50 focus:outline-none rounded p-5" />
          <button className="bg-fuchsia-400 hover:bg-fuchsia-500 active:bg-fuchsia-500 p-3 text-white text-lg font-bold self-end duration-200 ease-in-out rounded" type='submit'>Submit</button>
        </form>
        <ul className={`flex flex-wrap gap-2 w-full justify-center overflow-auto ease-in-out duration-300 transition-opacity ${(resList.length === 0) ? 'opacity-0' : 'opacity-100' }` }>
          {resMap}
        </ul>
      <footer className="mt-5 mb-2 text-violet-700"><a href="https://penajoia.com" target="_blank" rel="noreferrer" className="font-bold" >Marco Silva</a> - Front End Developer Intern Challenge - OpenAI (Fall 2022) - <a href="https://www.linkedin.com/in/mpenajoia/" target="_blank" rel="noreferrer" className="font-bold" >LinkedIn</a></footer>
      </div>
    </div>
  );
}

export default App;
